apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    project: expense
    module: backend
    environment: dev
spec:
  containers:
  # docker run -d --name nginx nginx
  - name: nginx
    image: nginx
